name = "wolfssl"
description = "WolfSSL encryption library and its Ada bindings"
version = "5.7.2"

authors = ["WolfSSL Team <support@wolfssl.com>"]
maintainers = ["Fernando Oleo Blanco <irvise@irvise.xyz>"]
maintainers-logins = ["Irvise"]
licenses = "GPL-2.0-only"
website = "https://www.wolfssl.com/"
project-files = ["wolfssl.gpr"]
tags = ["ssl", "tls", "embedded", "spark"]
