[package]
name = "wolfssl"
version = "0.1.0"
edition = "2024"

[features]
std = []

[build-dependencies]
bindgen = "0.72.1"
regex = "1.5"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
