name: Codespell test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  codespell:
    if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: codespell-project/actions-codespell@v2.1
      with:
        check_filenames: true
        check_hidden: true
          # Add comma separated list of words that occur multiple times that should be ignored (sorted alphabetically, case sensitive)
        ignore_words_list: adin,aNULL,brunch,carryIn,chainG,ciph,cLen,cliKs,dout,haveA,inCreated,inOut,inout,larg,LEAPYEAR,Merget,optionA,parm,parms,repid,rIn,userA,ser,siz,te,Te,HSI,
          # The exclude_file contains lines of code that should be ignored. This is useful for individual lines which have non-words that can safely be ignored.
        exclude_file: '.codespellexcludelines'
          # To skip files entirely from being processed, add it to the following list:
        skip: '*.cproject,*.der,*.mtpj,*.pem,*.vcxproj,.git,*.launch,*.scfg,*.revoked,./examples/asn1/dumpasn1.cfg,./examples/asn1/oid_names.h'
