name: Daily Merge and CodeSonar run
on:
  schedule:
    - cron: '30 * * * *'



jobs:
  Daily_Merge_and_CodeSonar_Analyze:
    permissions: write-all
    runs-on: self-hosted
    container:
      image: canuckmh/wolfssl-cso-builder:7.4p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      GITHUB_CAFILE: ".github/github.cert.pem"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      GITHUB_API_URL: https://api.github.com
      PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "OSS-Projects/WolfSSL-GitHub"
      PROJECT_NAME: "wolfssl"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_CSHOME: /opt/codesonar
      CSO_GITHUB: /opt/codesonar-github
      GITHUB_REPO_URL: "http://github.com/markhermeling/wolfssl"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:
      - name: Set parallelism and project name
        run: |
          echo "PARALLEL=`nproc`" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: release/daily
      - name: Merge from upstream
        run: |
           git fetch upstream
           git merge -Xours upstream/master
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name : configure
        run: ./autogen.sh ; ./configure --enable-all
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          ref: main
          path: codesonar-scripts
      - name: Build and Analyze
        run: python3 codesonar-scripts/build_and_analyze.py codesonar.conf make -j $PARALLEL
      - name: Upload SARIF to GitHub #Use this if you do not have GitHub Enterprise
        if: ${{ github.event.pull_request }}
        uses: actions/upload-artifact@v3
        with:
          name: SARIF file
          path: warnings.sarif
      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: warnings.md

