name: Merge from master
on:
  push:
    branches:
      - 'upstream/master'
      - 'release/daily'


jobs:
  Merge-from-Master:
    permissions: write-all
    runs-on: self-hosted
    container:
      image: canuckmh/wolfssl-cso-builder:7.4p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Do Something
        run: ls
