name: ipmitool Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION


jobs:
  build_wolfssl:
    name: Build wolfSSL
    if: github.repository_owner == 'wolfssl'
    # Just to keep it the same as the testing target
    runs-on: ubuntu-24.04
    # This should be a safe limit for the tests to run.
    timeout-minutes: 4
    steps:
      - name: Build wolfSSL
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          path: wolfssl
          configure: --enable-all
          install: true
          # Don't run tests as this config is tested in many other places
          check: false

      - name: tar build-dir
        run: tar -zcf build-dir.tgz build-dir

      - name: Upload built lib
        uses: actions/upload-artifact@v4
        with:
          name: wolf-install-ipmitool
          path: build-dir.tgz
          retention-days: 5

  build_ipmitool:
    strategy:
      fail-fast: false
      matrix:
        git_ref: [ c3939dac2c060651361fc71516806f9ab8c38901 ]
    name: ${{ matrix.git_ref }}
    if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-24.04
    needs: build_wolfssl
    steps:
      - name: Install dependencies
        run: export DEBIAN_FRONTEND=noninteractive && sudo apt-get update && sudo apt-get install -y libreadline-dev
      - name: Download lib
        uses: actions/download-artifact@v4
        with:
          name: wolf-install-ipmitool

      - name: untar build-dir
        run: tar -xf build-dir.tgz

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp

      - name: Build ipmitool
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: ipmitool/ipmitool
          ref: ${{ matrix.git_ref }}
          path: ipmitool
          patch-file: $GITHUB_WORKSPACE/osp/ipmitool/*-${{ matrix.git_ref }}.patch
          configure: --with-wolfssl=$GITHUB_WORKSPACE/build-dir
          # No checks included and not running since it depends on hardware
          check: false

      - name: Confirm built with wolfSSL
        working-directory: ipmitool
        run: |
          ldd src/ipmitool | grep wolfssl
          ldd src/ipmievd | grep wolfssl
