name: CI
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
    espressif:
        uses: ./.github/workflows/docker-Espressif.yml
    multi-compiler:
        uses: ./.github/workflows/multi-compiler.yml
    multi-arch:
        uses: ./.github/workflows/multi-arch.yml
    openwrt:
        uses: ./.github/workflows/docker-OpenWrt.yml
    os-check:
        uses: ./.github/workflows/os-check.yml
    async:
        uses: ./.github/workflows/async.yml
    stunnel:
        uses: ./.github/workflows/stunnel.yml
    openvpn:
        uses: ./.github/workflows/openvpn.yml
    hostap:
        uses: ./.github/workflows/hostap.yml
    nginx:
        uses: ./.github/workflows/nginx.yml
    zephyr:
        uses: ./.github/workflows/zephyr.yml
    hitch:
        uses: ./.github/workflows/hitch.yml
    curl:
        uses: ./.github/workflows/curl.yml
    krb5:
        uses: ./.github/workflows/krb5.yml
    packaging:
        uses: ./.github/workflows/packaging.yml
    memcached:
        uses: ./.github/workflows/memcached.yml
# TODO: Currently this test fails. Enable it once it becomes passing.        
#    haproxy:
#        uses: ./.github/workflows/haproxy.yml
