name: Packaging Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfssl:
    name: Package wolfSSL
    if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-24.04
    # This should be a safe limit for the tests to run.
    timeout-minutes: 10
    steps:
      - name: Checkout wolfSSL
        uses: actions/checkout@v4

      - name: Configure wolfSSL
        run: |
          autoreconf -ivf
          ./configure --enable-distro --enable-all \
            --disable-openssl-compatible-defaults --enable-intelasm \
            --enable-dtls13 --enable-dtls-mtu \
            --enable-sp-asm --disable-examples --disable-silent-rules

      - name: Make sure OPENSSL_COMPATIBLE_DEFAULTS is not present in options.h
        run: |
          ! grep OPENSSL_COMPATIBLE_DEFAULTS wolfssl/options.h

      - name: Build wolfSSL .deb
        run: make deb-docker

# disabled 20240919 -- broken target.
#      - name: Build wolfSSL .rpm
#        run: make rpm-docker

      - name: Confirm packages built
        run: |
          DEB_COUNT=$(find -name 'libwolfssl*.deb' | wc -l)
          if [ "$DEB_COUNT" != "3" ]; then
            echo Did not find exactly three deb packages!!!
            exit 1
          fi
# disabled 20240919 -- broken target.
#          RPM_COUNT=$(find -name 'wolfssl*.rpm' | wc -l)
#          if [ "$RPM_COUNT" != "4" ]; then
#            echo Did not find exactly four rpm packages!!!
#            exit 1
#          fi
